services:
  sleepy-mysql:
    container_name: sleepy-mysql
    image: mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    networks:
      - sleepy-backend
    volumes:
      - sleepy-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${SLEEPY_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "sleepy-db"
      MYSQL_ROOT_HOST: "%"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      timeout: 2s
      retries: 30
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
  sleepy-ssh:
    container_name: sleepy-ssh
    image: sleepy-ssh:latest
    restart: "always"
    ports:
      - "8888:8888"
    build:
      context: .docker/images/sleepy-ssh
      dockerfile: Dockerfile
  sleepy-backend:
    container_name: sleepy-backend
    image: sleepy-backend:latest
    restart: "always"
    ports:
      - "8081:8081"
      - "8082:8082"
      - "23365:23365"
    networks:
      - sleepy-backend
    volumes:
      - ./configs:/usr/src/app/configs
      - C:\Users\LamkasDev\Desktop\sleepy:/usr/src/sleepy
    environment:
      SLEEPY_MYSQL_PASSWORD: "${SLEEPY_MYSQL_PASSWORD}"
    depends_on:
      sleepy-mysql:
        condition: service_healthy
    build: 
      context: ./
      dockerfile: .docker/images/sleepy-backend/Dockerfile
    tty: yes
volumes:
  sleepy-mysql:
    external: true
networks:
  sleepy-backend:
    name: sleepy-backend